---
- name: playbook for ansible facts copy 
  hosts: all
  become: yes

  tasks:
  - name: gather facts
    copy:
      content: "{{ansible_hostname}} {{ansible_default_ipv4.address}}
                {{ansible_default_ipv4.macaddress}} {{ansible_processor_count}}\n"
      dest: /root/hostinfo.txt

