---
- name: Ansible setup
  hosts: all
  become: yes

  tasks:
    - name: create the user ansible 
      user:
        name: ansible
        password: $6$.VQ1wkix8bdcE0zh$CbCXVEwJqsTuePmyDl/Ke39BkmUnL8moH/gnJU3BV3PsjRV97IzLiHKIyK0a9Od79IgLBXXa4MljyAJRRAQxz1
        generate_ssh_key: yes
        ssh_key_bits: 2048
        ssh_key_file: .ssh/id_rsa
        comment: Ansible User 

    - name: Copy ansible ssh key to remote servers 
      authorized_key:
        user: ansible
        state: present
        key: "{{ lookup('file', '/home/ansible/.ssh/id_rsa.pub') }}"

    - name: Modify suders for admin privileges
      lineinfile:
        path: /etc/sudoers
        backup: yes
        line: 'ansible ALL=(ALL)       NOPASSWD: ALL'
