---
- name: setup httpd server
  hosts: all
  become: yes

  tasks:
    - name: install the httpd package
      yum:
        name:
          - httpd
          - firewalld
        state: present 

    - name: Download httpd config file
      get_url:
        url: http://static.sysadmindata.com/conf/httpd.conf
        dest: /etc/httpd/conf/httpd.conf
        backup: yes

    - name: Make index.html content
      copy:
        content: "Hello xxx\n"
        dest: /var/www/html/index.html
        force: no

    - name: use xxx with hostname 
      lineinfile:
        path: /var/www/html/index.html
        regexp: 'Hello xxx'
        line: "Hello from {{ ansible_hostname }}"

    - name: start the service
      service:
        name: httpd
        state: started
        enabled: yes

    - name: add the httpd service to firewall
      firewalld:
        service: http
        permanent: yes
        state: enabled
